### PR TITLE
CB-12397 Package .gitignore when publishing to npm

### PR DESCRIPTION
**Pull request by raphinesse**
For further details see discussion starting at:
https://github.com/apache/cordova-discuss/issues/69#issuecomment-390199958

### CODE REVIEW

**Comment by brodybits** [comment]
How was this tested?

**Comment by raphinesse** [comment]
`npm pack` with my local npm 6 on Linux. I already thought that we should test this with some test publish to see that there's no funny stuff happening.

**Comment by brodybits** [comment]
I tested as follows:
- <https://github.com/brodybits/cordova-create/tree/cb-package-gitignore-test1> branch on GitHub that includes the change in `github:raphinesse/cordova-app-hello-world#package-gitignore`
- <https://github.com/brodybits/cordova-lib/tree/cb-package-gitignore-test1> branch that includes `github:brodybits/cordova-create#cb-package-gitignore-test1` (cordova-create test branch above)
- <https://github.com/brodybits/cordova-cli/tree/cb-package-gitignore-test1> branch that includes `github:brodybits/cordova-lib#cb-package-gitignore-test1` (cordova-lib test branch above)

If I would try using my test version of cordova-cli to create a new project I would get a new project with `.npmignore`, NOT with `.gitignore`. I would not expect a different result if we would publish this change and update the upstream packages on NPM.

I think we still need a workaround solution like I proposed in apache/cordova-create#8 to resolve the issue, will reopen for discussion.

**Comment by raphinesse** [comment]
Thanks for the testing, I will take another look at this.

**Comment by raphinesse** [comment]
I also ran some tests with the following script (run as `node foo.js dest template`):
```js
var CordovaLogger = require('cordova-common').CordovaLogger;
CordovaLogger.get().setLevel(CordovaLogger.VERBOSE);

require('cordova-create')(process.argv[2], null, null, { lib: { www: {
    template: true,
    url: process.argv[3]
}}}).catch(function (err) {
    console.error(err);
    process.exitCode = 1;
});
```
Unfortunately I can confirm your results:
- Works as intended for local templates (files are simply copied by `cordova-create`)
- Renames `.gitignore` to `.npmignore` for templates fetched by `cordova-fetch`

What a bummer!

**Pull request closed without merging**
