### PR TITLE
CB-9009 default CSP needs to include 8472 for blackberry

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by jsoref** [comment]
@timwindsor

**Comment by timwindsor** [comment]
Works for me - required for use of any plugins.

**Comment by stevengill** [comment]
As long as this doesn't negatively impact other platforms, merge away.

**Comment by nikhilkh** [comment]
Is this required for development time experience or every app needs access to localhost port 8472 to run on the phone?

**Comment by jsoref** [comment]
It's required for runtime if an app (running on BlackBerry 10) has any plugins. The app doesn't actually talk to port 8472, it's just magically intercepted.

**Comment by csantanapr** [comment]
-1
hum this looks very ugly in the template. I don't like to have this in the default template. people might think that is a security whole.
In another platform like android, not picking android then that port will be expose, it will not get intercepted because is not blackberry

some options:
1. bb plugin to implement plugin hook, this is a new type of hook that plugins can implement 
If this is only required for BlackBerry, then the plugin for blackberry can implement a plugin hook to edit the index.html during after_prepare. it can parse the index.html look for the tag and if http://locahost:8472 doesn't exist then added.

2. the cordova.js for blackberry dynamically edits the csp tag in the dom
when cordova.js runs before setting up the plugin update the csp meta, I don't know if this is too late to change since index.html is already parsed, if this is not an option then take a look at option 1 above

**Comment by csantanapr** [comment]
@jengee you don't have to get tired of update the template every time, you can implement a user land cordova hook after_prepare [1] [2]
 
you can have a simple nodejs script or any other type of script, and parse the index.html after being copy to the platform/**/www/ and and check if csp is missing the value that you want "http://localhost:8247" and added there.

having an arbitrary localhost port open in csp, present for a common template will raise an eye brow of concerns for people using it in other platforms than blackberry.

[1] http://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html#Hooks%20Guide
[2] http://photokandy.tumblr.com/post/47426024187/cordova-cli-simple-hooks-and-merges

**Comment by purplecabbage** [comment]
Adding this to index.html should be a blackberry build step, I would expect this to only exist in the platform's www folder

**Comment by timwindsor** [comment]
Thanks everyone - I've got a potential solution that we're testing here. We can close this request.

**Pull request closed without merging**
