### PR TITLE
CB-11412 Update templates to designate template source dir

### PR DESCRIPTION
**Pull request by carynbear**

### CODE REVIEW

**Comment by stevengill** [comment]
Lets update version in the default config.xml to be 1.0.0 instead of 0.0.1

**Comment by stevengill** [comment]
Lets not add a `package.json` to template_src for now

**Comment by stevengill** [comment]
LGTM otherwise :)

**Comment by carynbear** [comment]
@stevengill removed package.json from template_src, changed config.xml version to 1.0.0

**Pull request closed without merging**
