### PR TITLE
CB-9712 CLI 5.3 breaks with node 3.3.3

### PR DESCRIPTION
**Pull request by daserge**
Added `index.js` so that the module can be required and resolved.

[Jira issue](https://issues.apache.org/jira/browse/CB-9712)

### CODE REVIEW

**Comment by omefire** [comment]
I think we should also update package.json to explicitly mention the entry point (index.js)

**Comment by daserge** [comment]
@omefire, thank you for review, 
I've addressed it.

**Comment by vladimir-kotikov** [comment]
LGTM :shipit:

**Comment by omefire** [comment]
LGTM!

**Pull request merged**
